<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<html lang="en">
<head>
<title>ref-ere-hex-pgo - SICStus Prolog</title>
<meta http-equiv="Content-Type" content="text/html">
<meta name="description" content="SICStus Prolog">
<meta name="generator" content="makeinfo 4.8">
<link title="Top" rel="start" href="index.html#Top">
<link rel="up" href="ref_002dere_002dhex.html#ref_002dere_002dhex" title="ref-ere-hex">
<link rel="next" href="ref_002dere_002dhex_002dhup.html#ref_002dere_002dhex_002dhup" title="ref-ere-hex-hup">
<link href="http://www.gnu.org/software/texinfo/" rel="generator-home" title="Texinfo Homepage">
<meta http-equiv="Content-Style-Type" content="text/css">
<style type="text/css"><!--
  pre.display { font-family:inherit }
  pre.format  { font-family:inherit }
  pre.smalldisplay { font-family:inherit; font-size:smaller }
  pre.smallformat  { font-family:inherit; font-size:smaller }
  pre.smallexample { font-size:smaller }
  pre.smalllisp    { font-size:smaller }
  span.sc    { font-variant:small-caps }
  span.roman { font-family:serif; font-weight:normal; } 
  span.sansserif { font-family:sans-serif; font-weight:normal; } 
--></style>
<link href="texinfo.css" rel="stylesheet" type="text/css">
</head>
<body>

<h5 class="subsubsection">4.15.3.1 Protecting a Particular Goal</h5>

<p><a name="index-on_005fexception_002f3-_0028built_002din_0029-1523"></a><a name="index-on_005fexception_002f3-_0028built_002din_0029-1524"></a>
<a name="index-catch_002f3-_0028built_002din_0029-1525"></a><a name="index-catch_002f3-_0028built_002din_0029-1526"></a>

   <p>The built-in predicate <code>on_exception/3</code> enables you to handle
exceptions to a specific goal:

<pre class="example">     <code>on_exception(</code><var>?ExceptionCode</var><code>, </code><var>:ProtectedGoal</var><code>, </code><var>:Handler</var><code>)</code>
</pre>
   <p><var>ProtectedGoal</var> is executed.  If all goes well, it will behave
just as if you had written <var>ProtectedGoal</var> without the
<code>on_exception/3</code> wrapper.  If an exception is raised while
<var>ProtectedGoal</var> is running, Prolog will abandon
<var>ProtectedGoal</var> entirely.  Any bindings made by
<var>ProtectedGoal</var> will be undone, just as if it had failed.  If the
exception occurred in the scope of a
<code>call_cleanup(</code><var>Goal</var><code>,</code><var>Cleanup</var>, <var>Cleanup</var> will be
called. 
<!-- If @code{undo/1} has issued goals to be run on backtracking, -->
<!-- those goals will be run. -->
Side-effects, such as asserts and retracts,
are not undone, just as they are not undone when a goal fails.  After
undoing the bindings, Prolog tries to unify the exception term raised
with the <var>ExceptionCode</var> argument.  If this unification succeeds,
<var>Handler</var> will be executed as if you had written

<pre class="display">     <var>ExceptionCode</var>=&lt;the actual exception term&gt;,
     <var>Handler</var>
</pre>
   <p>If this unification fails, Prolog will keep searching up the ancestor list
looking for another exception handler.  If it reaches Prolog's top level (or a
break level) without having found a call to <code>on_exception/3</code> with a matching
<var>ExceptionCode</var>, an appropriate error message is printed (using
<code>print_message/2</code>).

   <p><var>ProtectedGoal</var> need not be determinate.  That is, backtracking into
<var>ProtectedGoal</var> is possible, and the exception handler becomes reactivated
in this case.  However, if <var>ProtectedGoal</var> is determinate, the call
to <code>on_exception/3</code> is also determinate.

   <p>The <var>ProtectedGoal</var> is logically <em>inside</em> the <code>on_exception/3</code>
form, but the <var>Handler</var> is <em>not</em>.  If an exception is raised inside
the <var>Handler</var>, this <code>on_exception/3</code> form will <em>not</em> be
reactivated.  If you want an exception handler that protects itself,
you have to program it, perhaps like this:
<pre class="example">     recursive_on_exception_handler(Err, Goal, Handler) :-
         on_exception(Err, Goal,
             recursive_on_exception_handler(Err, Handler, Handler)).
</pre>
   <p>Certain built-in and library predicates rely on the exception mechanism,
so it is usually a bad idea to let <var>Pattern</var> be a variable,
matching any exception.  If it must be a variable, the <var>Handler</var>
should examine the exception and pass it on if it is not relevant
to the current invocation.

   <p>In a development system, any previously uncaught exception is
caught and an appropriate error message is printed before returning to
the top level.  In recursive calls to Prolog from C, uncaught exceptions
are returned back to C instead.  The printing of these and other
messages in a development system is handled by the predicate
<code>print_message/2</code> (see <a href="ref_002dmsg.html#ref_002dmsg">ref-msg</a>).

   <p><code>catch(</code><var>ProtectedGoal</var><code>, </code><var>ExceptionCode</var><code>, </code><var>Handler</var><code>)</code>
is the same as
<code>on_exception(</code><var>ExceptionCode</var><code>, </code><var>ProtectedGoal</var><code>, </code><var>Handler</var><code>)</code>.

<div class="logo">
<a href="http://www.sics.se/sicstus/">
<table><tr><td>&nbsp;</td></tr></table>
</a>
</div>
<div class="node">
<ul class="node">
<li><a href="index.html#Top">User's Manual</a>
<hr>
<li><a href="index.html#TOC">Table of Contents</a>
<li><a rel="next" accesskey="n" href="ref_002dere_002dhex_002dhup.html#ref_002dere_002dhex_002dhup">Next</a>
<li><a rel="up" accesskey="u" href="ref_002dere_002dhex.html#ref_002dere_002dhex">Up</a>
</ul>
</div>
<hr>
<a HREF="mailto:sicstus-support@sics.se?subject=Documentation%20feedback%20on%20html/sicstus/ref_002dere_002dhex_002dpgo.html&amp;body=Feedback%20on%20documentation%20node%20html/sicstus/ref_002dere_002dhex_002dpgo.html%20in%20User's%20Manual.">Send feedback on this subject.</mailto>
   </body></html>

